### ISSUE TITLE
Error accessing GitHub repository GuangchuangYu/yplots

### ISSUE THREAD

**Issue by llu5** [GuangchuangYu/yplot#1]
Hi,
Did you move the GitHub repository?
When I use yplot and publish to RPubs, I got error:
 Error: Unhandled Exception: Child Task 208233014 failed: Error building image: Error fetching yplot (0.0.2) source. Error accessing GitHub repository GuangchuangYu/yplots. HTTP 301: Moved Permanently
Execution halted

**Comment by GuangchuangYu** [comment]
check the repo name!!!

**Comment by llu5** [comment]
Thanks!
Li Lu
