### ISSUE TITLE
 Error building image: Error fetching yplot (0.0.2) source.

### ISSUE THREAD

**Issue by llu5** [GuangchuangYu/yplot#2]
Hi Guangchuang Yu,
The package works in my local PC in R studio. When I tried to publish to shinyapps.io, I got following error:

  error: Building package: yplot
################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 208245057 failed: Error building image: Error fetching yplot (0.0.2) source. Error accessing GitHub repository GuangchuangYu/yplots. HTTP 301: Moved Permanently
Execution halted

**Comment by GuangchuangYu** [comment]
duplicated, see <https://github.com/GuangchuangYu/yplot/issues/1>
